### ISSUE TITLE
Update repo name

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#26]
RiPLE has been re-named to Ripple. Should the repository should be re-named to reflect this?

**Comment by hkhosrav** [comment]
Yes, would you be able to the make the required changes?

**Comment by CaptainAchilles** [comment]
Not unless I have higher privileges for the repository. I think only the `owner` can manage that sort of thing. Best I can do is update the README

**Comment by hkhosrav** [comment]
It should renamed now
