### ISSUE TITLE
Make competency overview use single colour (#256)

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#33]
Having multiple colours in the competency overview does not look as nice as it should.

**Comment by hkhosrav** [comment]
I personally liked the multiple-colour version. Was there something in particular that you didn't like about it?

**Comment by CaptainAchilles** [comment]
I liked it as well - but I thought we decided in our discussions on Thursday to make it all a single colour?

**Comment by hkhosrav** [comment]
I think it must have been a misunderstanding. The one I had in my prototype had only one colour, but only because I didn't have easy access to the old version you had on the page. Maybe let's keep it as is for the time being.
