### ISSUE TITLE
Add visualization selection dropdown and data type for competency overview

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#34]
Visulisation types:
* Bar Chart
* Radar Chart
* Box Plot

Data types:
* Goal
* Cohort
* Previous Offering

**Comment by CaptainAchilles** [comment]
Users may not be familiar with the chart types, but material icons ships with icons for different charts; we could use those to help inform the user of which chart they want to see.

**Comment by hkhosrav** [comment]
Good idea. Plus this would be list that could potentially grow over time (e.g. addition of the topic dependency graphs)

**Comment by CaptainAchilles** [comment]
Available on branch `Ripple-#42`
