### ISSUE TITLE
Improvement on profile tab

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#40]
#37 introduced some interesting ideas for the project. As discussed today they can be moved into corresponding profile tabs, and the dashboard page can then show summaries of each profile tab.

*Engagement*: Alter the activity breakdown to show more comparative information about the user, and use the current implementation as a summary.

*Competencies*: A view which recommends the user a question most suitable for them

*Connections*: Review outstanding recommendations. This could either be a a link to the recommendations page, or a condensed accept/reject view.

*Achievements*: A small list of achievements they are close to

**Comment by hkhosrav** [comment]
Let's have another in-person discussion before we go ahead with implementing this. I'm still a little unsure about the idea of having questions being recommended through the profile page.

**Comment by CaptainAchilles** [comment]
As per our discussions:
---------
The *Competencies* page looks good with the new CompetencyOverview component, so it will be left alone.


Opened #44 to address the *Engagement* tab.
Opened #45 to address *Achievements*
Opened #46 as per discussions.

**Comment by CaptainAchilles** [comment]
Closing because superseded by created tickets.
