### ISSUE TITLE
Rendering in Safari

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#60]
Safari does not render many of the pages correctly due to what looks like a issue with flex inheritance.

**Comment by CaptainAchilles** [comment]
This seems to be caused by the page headings not expanding to full width, and in turn the application is rendering the content which should be *under* the headings next to the headings

**Comment by CaptainAchilles** [comment]
Not fully tested, but 9e80f6ac0fa888785494c87a358520b826ad768b should give better results.

**Comment by hkhosrav** [comment]
Perfect. We'll try merging it into the master branch soon.
