### ISSUE TITLE
Add gh-pages docs

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#61]
Add a `gh-pages` to the project

**Comment by CaptainAchilles** [comment]
This won't be viable until either an external server is set up to support the API calls, or a client faked API is implemented.

**Comment by hkhosrav** [comment]
Could we rely on the server set up on the zone?

**Comment by CaptainAchilles** [comment]
Yeah, it should work fine, but we'll have to make sure the API path isn't behind SSO and doesn't expose sensitive data.

**Comment by CaptainAchilles** [comment]
As per: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

The github settings need to be set up to use the `master/docs` directory.

**Comment by CaptainAchilles** [comment]
Everything seems to be working normally.
