### ISSUE TITLE
Fix charting legends

### ISSUE THREAD

**Issue by CaptainAchilles** [hkhosrav/RiPPLE-Client-side#64]
At the moment the chart legends are not very helpful in representing the chart content. The legend needs to be fixed to show the shape of the data point in the case of the scatter plot, and an explanation of the edge colour and thickness in the case of TDMs.

**Comment by CaptainAchilles** [comment]
ChartJS does provide some functionality for this - using the [http://www.chartjs.org/docs/latest/configuration/legend.html#html-legends](Custom Legend) callback. This seems to be the most straightforward solution without totally overriding ChartJS

**Comment by hkhosrav** [comment]
Seems like a good solution. Let's proceed with this.
